---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "主页导航"
subtitle: "Iatiah"
logo: "logo.png"
connectivityCheck: false
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false # '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default

# Optional theme customization (color overrrides)
# overrrides can also be done using CSS vars 
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "你好 !"
  icon: "fa fa-grin"
  content: "这是一个主页站点，把所有搭建过的网站都放在这里方便浏览使用。"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "主页"
    icon: "fab fa-web-awesome"
    url: "https://huhaitai.com"
    target: "_blank" # optional html a tag target attribute
  - name: "微博"
    icon: "fa-brands fa-microblog"
    url: "https://t.huhaitai.com/"
    target: "_blank"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Google平台"
    icon: "fa-brands fa-google"
    items:
      - name: "博客"
        icon: "fa-solid fa-blog"
        subtitle: "搭建在google appengine平台上的博客程序"
        tag: "blog"
        url: "https://b.huhaitai.com"
      - name: "私人博客"
        icon: "fa-solid fa-stop"
        subtitle: "Blogger平台上的日记博客"
        tag: "blog"
        url: "https://bi.huhaitai.com"
      - name: "地点"
        icon: "fa-solid fa-location-dot"
        subtitle: "每2个小时上传一次自己的位置，已废弃"
        tag: "tool"
        url: "https://locate.huhaitai.com"
  - name: "Cloudflare平台"
    icon: "fa-brands fa-cloudflare"
    items:
      - name: "图片"
        icon: "fa-solid fa-image"
        subtitle: "一个图床"
        tag: "tool"
        url: "https://img.huhaitai.com"
      - name: "文本"
        icon: "fa-solid fa-note-sticky"
        subtitle: "一个文本分享工具"
        tag: "tool"
        url: "https://note.huhaitai.com"
      - name: "剪贴板"
        icon: "fa-solid fa-clipboard"
        subtitle: "临时剪贴板，另一个文本分享工具"
        tag: "tool"
        url: "https://pb.huhaitai.com"
      - name: "文件"
        icon: "fa-solid fa-file"
        subtitle: "临时文件分享"
        tag: "tool"
        url: "https://fs.huhaitai.com" 
      - name: "短链接"
        icon: "fa-solid fa-link"
        subtitle: "短链接工具，有后台分析系统"
        tag: "tool"
        url: "https://link.huhaitai.com"
      - name: "TV"
        icon: "fa-solid fa-tv"
        subtitle: "LibreTV，一个观看影视的工具"
        tag: "tool"
        url: "https://tv.huhaitai.com"
      - name: "频道"
        icon: "fa-solid fa-user-group"
        subtitle: "基于BroadcastChannel，把telegram的群消息转变为微博"
        tag: "blog"
        url: "https://bc.huhaitai.com"     
  - name: "Netlify平台"
    icon: "fa-solid fa-server"
    items:
      - name: "IT Tools"
        icon: "fa-solid fa-toolbox"
        subtitle: "IT人员在线工具"
        tag: "tool"
        url: "https://tools.huhaitai.com"
  - name: "Github平台"
    icon: "fa-brands fa-github"
    items:
      - name: "Markdown text editor"
        icon: "fa-brands fa-markdown"
        subtitle: "Markdown文本编辑器"
        tag: "tool"
        url: "https://haitai.github.io"
